[Dataset]
path-root     = /path/to/dataset
path-windows  = processed/processed_values/windows
path-openface = processed/participant_data/
file-annotation = annotation_%s.csv
file-openface   = video_*_%s_explainee.csv
file-survey     = raw/survey.csv
file-token-list = processed/token_list.pkl
conditions = stress, neutral
states = understanding, listening, confusion

[Features]
action-units = 
    "name","feature","description","muscles"
    "AU01","AU01_r","Inner Brow Raiser","Frontalis, pars medialis"
    "AU02","AU02_r","Outer Brow Raiser","Frontalis, pars lateralis"
    "AU04","AU04_r","Brow Lowerer","Corrugator supercilii, Depressor supercilii"
    "AU05","AU05_r","Upper Lid Raiser","Levator palpebrae superioris"
    "AU06","AU06_r","Cheek Raiser","Orbicularis oculi, pars orbitalis"
    "AU07","AU07_r","Lid Tightener","Orbicularis oculi, pars palpebralis"
    "AU09","AU09_r","Nose Wrinkler","Levator labii superioris alaquae nasi"
    "AU10","AU10_r","Upper Lip Raiser","Levator labii superioris"
    #"AU11","AU11_r","Nasolabial Deepener","Zygomaticus minor"
    "AU12","AU12_r","Lip Corner Puller","Zygomaticus major"
    #"AU13","AU13_r","Cheek Puffer","Levator anguli oris (a.k.a. Caninus)"
    "AU14","AU14_r","Dimpler","Buccinator"
    "AU15","AU15_r","Lip Corner Depressor","Depressor anguli oris (a.k.a. Triangularis)"
    #"AU16","AU16_r","Lower Lip Depressor","Depressor labii inferioris"
    "AU17","AU17_r","Chin Raiser","Mentalis"
    #"AU18","AU18_r","Lip Puckerer","Incisivii labii superioris and Incisivii labii inferioris"
    "AU20","AU20_r","Lip stretcher","Risorius w/ platysma"
    #"AU22","AU22_r","Lip Funneler","Orbicularis oris"
    "AU23","AU23_r","Lip Tightener","Orbicularis oris"
    #"AU24","AU24_r","Lip Pressor","Orbicularis oris"
    "AU25","AU25_r","Lips part**","Depressor labii inferioris or relaxation of Mentalis, or Orbicularis oris"
    "AU26","AU26_r","Jaw Drop","Masseter, relaxed Temporalis and internal Pterygoid"
    #"AU27","AU27_r","Mouth Stretch","Pterygoids, Digastric"
    "AU28","AU28_c","Lip Suck","Orbicularis oris"
    #"AU41","AU41_r","Lid droop**","Relaxation of Levator palpebrae superioris"
    #"AU42","AU42_r","Slit","Orbicularis oculi"
    #"AU43","AU43_r","Eyes Closed","Relaxation of Levator palpebrae superioris; Orbicularis oculi, pars palpebralis"
    #"AU44","AU44_r","Squint","Orbicularis oculi, pars palpebralis"
    "AU45","AU45_c","Blink","Relaxation of Levator palpebrae superioris; Orbicularis oculi, pars palpebralis"
    #"AU46","AU46_r","Wink","Relaxation of Levator palpebrae superioris; Orbicularis oculi, pars palpebralis"

[Models]
# MLP
mlp-hidden-layers = 4
mlp-layer-neurons = 600